name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          # platforms: linux/amd64
          tags: mynginx:latest
          outputs: type=docker,dest=/tmp/image.tar

      - name: List
        env:
          TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}
          REGION: us-east-1
          SBOM: true # Saves SBOM to SBOM.json so you can export it as an artifact later.
          MALWARE_SCAN: true # Enable malware scan.
          THRESHOLD: "critical"
        run: |
          # Install tmas latest version
          curl -s -L https://gist.github.com/raphabot/abae09b46c29afc7c3b918b7b8ec2a5c/raw/ | bash

          tmas scan "$(if [ "$MALWARE_SCAN" = true ]; then echo "--malwareScan"; fi)" -r "$REGION" docker-archive:/tmp/image.tar "$(if [ "$SBOM" = true ]; then echo "--saveSBOM"; fi)" | tee result.json

          if [ "$SBOM" = true ]; then mv SBOM_* sbom.json; fi

          fail=0
          [ "${THRESHOLD}" = "any" ] && \
            [ $(jq '.totalVulnCount' result.json) -ne 0 ] && fail=1

          [ "${THRESHOLD}" = "critical" ] && \
            [ $(jq '.criticalCount' result.json) -ne 0 ] && fail=2

          [ "${THRESHOLD}" = "high" ] && \
            [ $(jq '.highCount + .criticalCount' result.json) -ne 0 ] && fail=3

          [ "${THRESHOLD}" = "medium" ] && \
            [ $(jq '.mediumCount + .highCount + .criticalCount' result.json) -ne 0 ] && fail=4

          [ "${THRESHOLD}" = "low" ] &&
            [ $(jq '.lowCount + .mediumCount + .highCount + .criticalCount' result.json) -ne 0 ] && fail=5

          # [ $(jq '.malware.scanResult' result.json) -ne 0 ] && fail=6

          [ $fail -eq 6 ] && echo Malware; exit 1

          [ $fail -ne 0 ] && echo Vulnerability threshold exceeded; exit 1

      - name: Upload Scan Result Artifact
        uses: actions/upload-artifact@v3
        with:
          name: scan-result
          path: result.json
          retention-days: 30

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json
          retention-days: 30
